; © Alessandro Castagna — 321.al / EVOLAB
; POI•LOVE. Alzati il 21/08/2026: con 10 MB le foto dei telefoni passavano per un
; soffio e i video no. Adesso il tetto e' quello che accettano gli endpoint:
; video fino a 400 MB, audioguide 300 MB, foto qualche MB.
upload_max_filesize = 400M
post_max_size = 400M
max_execution_time = 300
memory_limit = 512M
